hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    ycloud-uaa:
      path: /ycloud-uaa/**
      serviceId: ycloud-uaa
      stripPrefix: true
      custom-sensitive-headers: true
      sensitiveHeaders:
    ycloud-blog:
      path: /ycloud-blog/**
      serviceId: ycloud-blog
      stripPrefix: true
      custom-sensitive-headers: true
      sensitiveHeaders:
    ycloud-log:
      path: /ycloud-log/**
      serviceId: ycloud-log
      stripPrefix: true
      sensitiveHeaders:
      custom-sensitive-headers: true

server:
  port: 5000
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: debug
  file: logs/${spring.application.name}.log

