spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3306/ycloud01_user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  rabbitmq:
    host: local.rabbitmq.com
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
mybatis:
  type-aliases-package: com.yumenghu.uaa.domain
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
# port
server:
  port: 0
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: info
    com.yumenghu: debug
  file: logs/${spring.application.name}.log