spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ycloud.mysql.com:3306/ycloud_log?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  rabbitmq:
    host: ycloud.rabbitmq.com
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
mybatis:
  type-aliases-package: com.yumenghu.log.domain
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://local.gateway.com:5000/ycloud-uaa/user/user-me
      prefer-token-info: false
# port
server:
  port: 0
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
logging:
  level:
    root: info
    com.yumenghu: debug
  file: logs/${spring.application.name}.log